# ---------------------------------------
# for Vim8 to activate denite and deoplete
# ---------------------------------------

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

# ---------------------------------------
# funtamental plugins
# ---------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'h1mesuke/unite-outline'
[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'jimsei/winresizer'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

# ---------------------------------------
# denite
# ---------------------------------------

[[plugins]]                               
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_post_source = '''
    call denite#custom#var('file_rec', 'command',
    \ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
    call denite#custom#var('grep', 'command',
    \ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
    call denite#custom#var('grep', 'default_opts', [])
    call denite#custom#var('grep', 'recursive_opts', [])
'''

# ---------------------------------------
# deoplete and other completion plugins
# ---------------------------------------

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#if = "has('nvim')"
#on_i = 1
#on_event = 'InsertCharPre'
##hook_source = '''
#  let g:deoplete#enable_at_startup = 1
#  let g:deoplete#auto_complete_start_length = 1
#  let g:deoplete#enable_camel_case = 0
#  let g:deoplete#enable_ignore_case = 0
#  let g:deoplete#enable_refresh_always = 1
#  let g:deoplete#enable_smart_case = 1
#  let g:deoplete#file#enable_buffer_path = 1
#  let g:deoplete#max_list = 10000
#  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
#        \ neosnippet#expandable_or_jumpable() ?
#        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
#'''

[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo =  'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo =  'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo =  'prabirshrestha/asyncomplete-file.vim'
[[plugins]]
repo =  'natebosch/vim-lsc'
[[plugins]]
repo =  'prabirshrestha/asyncomplete-neosnippet.vim'
#[[plugins]]
# https://github.com/prabirshrestha/vim-lsp/wiki/Servers-PHP
#repo =  'felixfbecker/php-language-server'
#hook_post_update = '''
#if executable('php') && executable('composer')
#    call system('composer install && composer run-script parse-stubs')
#endif
#'''
[[plugins]]
repo =  'chemzqm/denite-git'

# ---------------------------------------
# code jump (gtags)
# ---------------------------------------

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
[[plugins]]
repo = 'jsfaint/gen_tags.vim'
[[plugins]]
repo = 'ozelentok/denite-gtags'

# ---------------------------------------
# themes
# ---------------------------------------

[[plugins]]
repo = 'iCyMind/NeoSolarized'
[[plugins]]
repo = 'zcodes/vim-colors-basic'
[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
[[plugins]]
repo = 'rakr/vim-one'
[[plugins]]
repo = 'jacoborus/tender.vim'
[[plugins]]
repo = 'hauleth/blame.vim'
[[plugins]]
repo = 'raphamorim/lucario'
[[plugins]]
repo = 'dikiaap/minimalist'
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'sonph/onehalf'
[[plugins]]
repo = 'dracula/vim'
[[plugins]]
repo = 'gosukiwi/vim-atom-dark'
[[plugins]]
repo = 'kristijanhusak/vim-hybrid-material'
[[plugins]]
repo = 'connorholyday/vim-snazzy'

