# funtamental plugins
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neoyank.vim'
[[plugins]]
repo = 'Shougo/neocomplete'
[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'soramugi/auto-ctags.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'h1mesuke/unite-outline'
[[plugins]]
repo = 'tomtom/tcomment_vim'
[[plugins]]
repo = 'jimsei/winresizer'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# themes
[[plugins]]
repo = 'jacoborus/tender.vim'
[[plugins]]
repo = 'hauleth/blame.vim'

[[plugins]]
repo = 'neomake/neomake'                  
hook_add = '''                            
autocmd! BufWritePost * Neomake           
'''  

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]                               
repo = 'neomake/neomake'                  
hook_add = '''                            
autocmd! BufWritePost * Neomake           
'''

[[plugins]]                               
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'
hook_add = '''
nnoremap [denite] <Nop>
nmap <Space>f [denite]

nmap <silent> [denite]w :<C-u>Denite file -highlight-mode-insert=Search<CR>
nmap <silent> [denite]t :<C-u>Denite filetype -highlight-mode-insert=Search<CR>
nmap <silent> [denite]f :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>
nmap <silent> [denite]m :<C-u>Denite file_mru -highlight-mode-insert=Search<CR>
nmap <silent> [denite]l :<C-u>Denite line -highlight-mode-insert=Search<CR>
nmap <silent> [denite]y :<C-u>Denite neoyank -highlight-mode-insert=Search<CR>
nmap <silent> [denite]b :<C-u>Denite buffer -highlight-mode-insert=Search<CR>
nmap <silent> [denite]o :<C-u>Denite outline -highlight-mode-insert=Search<CR>
nmap <silent> [denite]g :<C-u>Denite grep -highlight-mode-insert=Search<CR>
nmap <silent> <C-p> :<C-u>Denite file_rec -highlight-mode-insert=Search<CR>

"Denite filetype<CR>
"Denite file_rec<CR>
"Denite grep<CR>
"DeniteCursorWord grep<CR>
"Denite -resume<CR>
""Denite -resume -immediately -select=+1<CR>
nmap <silent> <C-u>- :<C-u>Denite -resume -immediately -select=-1<CR>
nmap <silent> <C-u><C-d> :<C-u>call denite#start([{'name': 'file_rec', 'args': ['~/dotfiles']}])<CR>
nnoremap ml :<C-u>call denite#start([{'name': 'file_rec', 'args': [g:memolist_path]}])<CR>
'''

hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#var('grep', 'command',
\ ['pt', '--nogroup', '--nocolor', '--smart-case', '--hidden'])
call denite#custom#var('grep', 'default_opts', [])
call denite#custom#var('grep', 'recursive_opts', [])
'''
